(()=>{
'use strict';
const {VERT,FRAG}=window.HELIOS_SHADER;
const $=s=>document.querySelector(s),body=document.body,canvas=$('#world'),gate=$('#gate'),enter=$('#enter'),finale=$('.finale'),replay=$('.replay'),reticle=$('.reticle'),status=$('.status'),soundButton=$('.sound'),soundText=soundButton.lastElementChild,chapterNo=$('.chapterNo'),chapterIndex=$('.chapterIndex'),chapterTitle=$('.chapterTitle'),chapterHint=$('.chapterHint'),clock=$('.clock'),chapterBox=$('.chapter'),beacons=[...document.querySelectorAll('.beacon')],energyValue=$('.energyValue');
const chapters=[['00 / VOID','SIGNAL ACQUIRED','STEER · BOOST · PULSE'],['01 / THRESHOLD','RING TRANSIT','CAMERA LINKED'],['02 / ENGINE','CORE CONTACT','PULSE AVAILABLE'],['03 / CITY','MONOLITH FIELD','BOOST ONLINE'],['04 / DAWN','HORIZON WAKE','FINAL APPROACH']];
let gl,program,uniforms={},start=0,last=0,started=false,done=false,j=0,targetJ=0,baseSpeed=1/78,pointer={x:0,y:0,tx:0,ty:0},holding=false,boost=0,pulse=0,pulseClock=0,low=matchMedia('(max-width:760px),(hover:none) and (pointer:coarse)').matches||(navigator.hardwareConcurrency||4)<=4,reduced=matchMedia('(prefers-reduced-motion:reduce)').matches,quality=low?0:1,targetFps=reduced?15:low?24:30,frameTimes=[],audio=null,lastChapter=-1,charge=0,collected=[false,false,false],chapterTimer=0;
function compile(type,src){const s=gl.createShader(type);gl.shaderSource(s,src);gl.compileShader(s);if(!gl.getShaderParameter(s,gl.COMPILE_STATUS))throw new Error(gl.getShaderInfoLog(s));return s}
function initGL(){try{gl=canvas.getContext('webgl2',{alpha:false,antialias:false,depth:false,stencil:false,powerPreference:'high-performance',desynchronized:true});if(!gl)throw new Error('WebGL 2 unavailable');const vs=compile(gl.VERTEX_SHADER,VERT),fs=compile(gl.FRAGMENT_SHADER,FRAG);program=gl.createProgram();gl.attachShader(program,vs);gl.attachShader(program,fs);gl.linkProgram(program);if(!gl.getProgramParameter(program,gl.LINK_STATUS))throw new Error(gl.getProgramInfoLog(program));gl.useProgram(program);const b=gl.createBuffer();gl.bindBuffer(gl.ARRAY_BUFFER,b);gl.bufferData(gl.ARRAY_BUFFER,new Float32Array([-1,-1,1,-1,-1,1,-1,1,1,-1,1,1]),gl.STATIC_DRAW);const loc=gl.getAttribLocation(program,'aPosition');gl.enableVertexAttribArray(loc);gl.vertexAttribPointer(loc,2,gl.FLOAT,false,0,0);['uResolution','uPointer','uTime','uJourney','uBoost','uPulse','uCharge','uQuality'].forEach(k=>uniforms[k]=gl.getUniformLocation(program,k));resize();body.classList.add('ready');requestAnimationFrame(frame)}catch(e){console.error('[HELIOS]',e);body.classList.add('ready','no-webgl');status.textContent='LIGHTWEIGHT MODE';status.classList.add('show')}}
function resize(){if(!gl)return;const dpr=Math.min(devicePixelRatio||1,low?1:1.35);const maxPx=low?700000:1900000;let scale=low?.72:.94;const px=innerWidth*innerHeight*dpr*dpr*scale*scale;if(px>maxPx)scale*=Math.sqrt(maxPx/px);canvas.width=Math.max(1,Math.round(innerWidth*dpr*scale));canvas.height=Math.max(1,Math.round(innerHeight*dpr*scale));gl.viewport(0,0,canvas.width,canvas.height)}
function frame(now){requestAnimationFrame(frame);if(!gl)return;const interval=1000/targetFps;if(now-last<interval*.88)return;const dt=Math.min(.06,Math.max(.001,(now-last)/1000));last=now;frameTimes.push(dt);if(frameTimes.length>90)frameTimes.shift();pointer.x+=(pointer.tx-pointer.x)*(1-Math.exp(-dt*5));pointer.y+=(pointer.ty-pointer.y)*(1-Math.exp(-dt*5));boost+=(Number(holding)-boost)*(1-Math.exp(-dt*7));if(started&&!done){targetJ+=dt*baseSpeed*(1+boost*2.4);if(targetJ>=1){targetJ=1;done=true;setTimeout(()=>finale.classList.add('show'),900)}}j+=(targetJ-j)*(1-Math.exp(-dt*4.8));pulseClock+=dt;pulse=Math.max(0,pulse-dt*1.35);document.documentElement.style.setProperty('--progress',j.toFixed(5));document.documentElement.style.setProperty('--px',pointer.x.toFixed(3));document.documentElement.style.setProperty('--py',pointer.y.toFixed(3));document.documentElement.style.setProperty('--pulse-ui',Math.max(0,pulse*.65).toFixed(3));const ci=Math.min(4,Math.floor(j*5.0001));const ch=chapters[ci];if(ci!==lastChapter){lastChapter=ci;chapterBox.classList.add('reveal');clearTimeout(chapterTimer);chapterTimer=setTimeout(()=>chapterBox.classList.remove('reveal'),2300)}chapterNo.textContent=ch[0];chapterIndex.textContent=ch[0];chapterTitle.textContent=ch[1];chapterHint.textContent=ch[2];const windows=[[.11,.2],[.43,.57],[.66,.79]];beacons.forEach((b,i)=>b.classList.toggle('active',!collected[i]&&j>windows[i][0]&&j<windows[i][1]));document.documentElement.style.setProperty('--charge',(charge/3).toFixed(3));document.documentElement.style.setProperty('--boost-ui',boost.toFixed(3));energyValue.textContent=charge+' / 3';const sec=Math.floor(j*78);clock.textContent=`${String(Math.floor(sec/60)).padStart(2,'0')}:${String(sec%60).padStart(2,'0')}`;gl.useProgram(program);gl.uniform2f(uniforms.uResolution,canvas.width,canvas.height);gl.uniform2f(uniforms.uPointer,pointer.x,pointer.y);gl.uniform1f(uniforms.uTime,(now-(start||now))/1000);gl.uniform1f(uniforms.uJourney,j);gl.uniform1f(uniforms.uBoost,boost);gl.uniform1f(uniforms.uPulse,pulseClock);gl.uniform1f(uniforms.uCharge,charge/3);gl.uniform1f(uniforms.uQuality,quality);gl.drawArrays(gl.TRIANGLES,0,6);audio?.update(j,boost,pulse)}
function begin(){started=true;start=performance.now();gate.classList.add('is-hidden');body.classList.add('playing');status.textContent='SYSTEM ONLINE';status.classList.add('show');setTimeout(()=>status.classList.remove('show'),1300)}
function firePulse(){pulse=1;pulseClock=0;reticle.classList.remove('pulse');void reticle.offsetWidth;reticle.classList.add('pulse');audio?.impact()}
function setPointer(clientX,clientY){pointer.tx=clientX/innerWidth*2-1;pointer.ty=-(clientY/innerHeight*2-1)}
enter.addEventListener('click',begin);replay.addEventListener('click',()=>{j=targetJ=0;done=false;finale.classList.remove('show');start=performance.now();body.classList.add('playing')});addEventListener('resize',resize,{passive:true});addEventListener('pointermove',e=>setPointer(e.clientX,e.clientY),{passive:true});addEventListener('pointerdown',e=>{if(!started)return;holding=true;setPointer(e.clientX,e.clientY);firePulse()},{passive:true});addEventListener('pointerup',()=>holding=false,{passive:true});addEventListener('pointercancel',()=>holding=false,{passive:true});addEventListener('keydown',e=>{if(e.code==='Space'){e.preventDefault();holding=true}if(e.key.toLowerCase()==='e')firePulse();if(e.key==='ArrowLeft'||e.key.toLowerCase()==='a')pointer.tx-=.16;if(e.key==='ArrowRight'||e.key.toLowerCase()==='d')pointer.tx+=.16;if(e.key==='ArrowUp'||e.key.toLowerCase()==='w')pointer.ty+=.12;if(e.key==='ArrowDown'||e.key.toLowerCase()==='s')pointer.ty-=.12});addEventListener('keyup',e=>{if(e.code==='Space')holding=false});
beacons.forEach((b,i)=>b.addEventListener('click',e=>{e.stopPropagation();if(collected[i])return;collected[i]=true;charge++;firePulse();status.textContent='SIGNAL '+String(i+1).padStart(2,'0')+' ABSORBED';status.classList.add('show');setTimeout(()=>status.classList.remove('show'),1200);targetJ=Math.min(1,targetJ+.035)}));
function createAudio(){const C=window.AudioContext||window.webkitAudioContext,ctx=new C(),master=ctx.createGain(),filter=ctx.createBiquadFilter(),comp=ctx.createDynamicsCompressor();master.gain.value=0;filter.type='lowpass';filter.frequency.value=620;filter.Q.value=.9;filter.connect(comp).connect(master).connect(ctx.destination);const oscs=[[43.65,'sine',.16],[65.41,'triangle',.065],[98,'sine',.022]].map(([f,type,g])=>{const o=ctx.createOscillator(),gain=ctx.createGain();o.frequency.value=f;o.type=type;gain.gain.value=g;o.connect(gain).connect(filter);o.start();return{o,gain}});const len=ctx.sampleRate*2,buf=ctx.createBuffer(1,len,ctx.sampleRate),data=buf.getChannelData(0);for(let i=0;i<len;i++)data[i]=(Math.random()*2-1);const noise=ctx.createBufferSource(),nf=ctx.createBiquadFilter(),ng=ctx.createGain();noise.buffer=buf;noise.loop=true;nf.type='bandpass';nf.frequency.value=480;nf.Q.value=.7;ng.gain.value=.025;noise.connect(nf).connect(ng).connect(filter);noise.start();return{ctx,master,filter,ng,oscs,on:false,async toggle(){if(ctx.state==='suspended')await ctx.resume();this.on=!this.on;master.gain.cancelScheduledValues(ctx.currentTime);master.gain.linearRampToValueAtTime(this.on?.24:0,ctx.currentTime+.65);return this.on},update(p,b,pu){const t=ctx.currentTime;filter.frequency.setTargetAtTime(320+p*1900+b*900,t,.16);ng.gain.setTargetAtTime(.018+b*.055,t,.18);oscs.forEach((x,i)=>x.o.detune.setTargetAtTime(p*240+i*8+b*24,t,.24))},impact(){if(!this.on)return;const t=ctx.currentTime,o=ctx.createOscillator(),g=ctx.createGain();o.type='sine';o.frequency.setValueAtTime(120,t);o.frequency.exponentialRampToValueAtTime(28,t+.75);g.gain.setValueAtTime(.18,t);g.gain.exponentialRampToValueAtTime(.0001,t+.85);o.connect(g).connect(master);o.start(t);o.stop(t+.9)}}}
soundButton.addEventListener('click',async()=>{try{if(!audio)audio=createAudio();const on=await audio.toggle();soundButton.setAttribute('aria-pressed',String(on));soundText.textContent=on?'SOUND / ON':'SOUND / OFF'}catch(e){console.warn('[HELIOS audio]',e);soundText.textContent='SOUND / N/A'}});
window.__HELIOS_TEST__={setJourney(v){targetJ=j=Math.max(0,Math.min(1,v));started=true;body.classList.add('playing');gate.classList.add('is-hidden');done=v>=1;finale.classList.toggle('show',done)},pulse:firePulse,state(){return{journey:j,target:targetJ,started,done,canvas:[canvas.width,canvas.height],quality,low,fps:frameTimes.length?1/(frameTimes.reduce((a,b)=>a+b,0)/frameTimes.length):0,webgl:!!gl,chapter:Math.min(4,Math.floor(j*5.0001)),charge,collected:[...collected]}},readCenter(){if(!gl)return null;const p=new Uint8Array(4);gl.readPixels(canvas.width>>1,canvas.height>>1,1,1,gl.RGBA,gl.UNSIGNED_BYTE,p);return Array.from(p)}};
initGL();
})();
